import Head from 'next/head';
import JobForm from '@/components/job-form/job-form.component';
import JobList from '@/components/job-list/job-list.component';
import styles from './../styles/home.module.css';

export default function Home() {
  /**
   * Home
   * The home page
   */
  return (
    <>
      <Head>
        <title>IJS | Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container'>
        <h1 className={`${styles.title}`}>
          Indeed <br /> Job Scraper
        </h1>
        <JobForm />
        <JobList />
      </main>
    </>
  );
}
